swagger: "2.0"

info:
  title: IPFSWebService
  description:
    This specification defines a minimalist subset of the HTTP API for IPFS.
  version: 0.0.1

host: 127.0.0.1:5001
basePath: /api/v0
schemes:
  - http

paths:

  /add:
    post:
      summary:
        Add a file or directory to ipfs.
      operationId: add
      consumes:
        - multipart/form-data
      produces:
        - application/json
      parameters:
        - in: formData
          name: file
          type: file
          description: |
            This endpoint expects a file in the body of the request
            as ‘multipart/form-data’.
          required: true
      responses:
        200:
          description: OK
          schema:
            $ref: '#/definitions/AddResponse'

definitions:

    AddResponse:
      description:
        The object which represents a response from the server.
      type: object
      properties:
        Name:
          type: string
          example: "The Cathedral and the Bazaar.pdf"
        Hash:
          type: string
          example: QmU6A9DYK4N7dvgcrmr9YRjJ4RNxAE6HnMjBBPLGedqVT7
        Size:
          type: string
          example: "193960"
      required:
      - Name
      - Hash
      - Size
