//
// InlineResponse200.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse200: Codable {

    public var name: String?
    public var hash: String?
    public var size: Int64?

    public init() {}

}
