//
// InlineResponse200.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class InlineResponse200: Codable {

    public var Name: String?
    public var Hash: String?
    public var Size: String?

    public init() {}

}
