//
// Key.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class Key: Codable {

    /** The name of the key as given to the keygen API. */
    public var name: String
    /** The generated key for usage with IPNS. */
    public var id: String


    
    public init(name: String, id: String) {
        self.name = name
        self.id = id
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(name, forKey: "Name")
        try container.encode(id, forKey: "Id")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        name = try container.decode(String.self, forKey: "Name")
        id = try container.decode(String.self, forKey: "Id")
    }
}

