//
// RenameKeyResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class RenameKeyResponse: Codable {

    /** The previous name of the key. */
    public var was: String
    /** The new name of the key. */
    public var now: String
    /** The generated key for usage with IPNS. */
    public var id: String
    /** Indicates whether an existing key was overriden. */
    public var overwrite: Bool?


    
    public init(was: String, now: String, id: String, overwrite: Bool?) {
        self.was = was
        self.now = now
        self.id = id
        self.overwrite = overwrite
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(was, forKey: "Was")
        try container.encode(now, forKey: "Now")
        try container.encode(id, forKey: "Id")
        try container.encodeIfPresent(overwrite, forKey: "Overwrite")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        was = try container.decode(String.self, forKey: "Was")
        now = try container.decode(String.self, forKey: "Now")
        id = try container.decode(String.self, forKey: "Id")
        overwrite = try container.decodeIfPresent(Bool.self, forKey: "Overwrite")
    }
}

