//
// AddResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The object which represents a response from the server. */
open class AddResponse: JSONEncodable {

    public var name: String?
    public var hash: String?
    public var size: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["Name"] = self.name
        nillableDictionary["Hash"] = self.hash
        nillableDictionary["Size"] = self.size

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
