//
// KeygenResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class KeygenResponse: JSONEncodable {

    /** The name of the key as given to the keygen API. */
    public var name: String?
    /** The generated key for usage with IPNS. */
    public var id: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["Name"] = self.name
        nillableDictionary["Id"] = self.id

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

