//
// PinResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


open class PinResponse: JSONEncodable {

    /** A list of pinned objects. */
    public var pins: [String]?
    public var progress: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["Pins"] = self.pins?.encodeToJSON()
        nillableDictionary["Progress"] = self.progress

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}

