//
// PublishResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


/** The object which represents a response from the server. */
open class PublishResponse: JSONEncodable {

    /** The name under which the value was published. By default, this will be the peer ID (i.e. the hash of the node&#39;s public key).  */
    public var name: String?
    /** The resource to which the name now resolves.  */
    public var value: String?

    public init() {}

    // MARK: JSONEncodable
    open func encodeToJSON() -> Any {
        var nillableDictionary = [String:Any?]()
        nillableDictionary["Name"] = self.name
        nillableDictionary["Value"] = self.value

        let dictionary: [String:Any] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
