//
// ResolveResponse.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation



open class ResolveResponse: Codable {

    /** The path to which the name resolved.  */
    public var path: String


    
    public init(path: String) {
        self.path = path
    }
    

    // Encodable protocol methods

    public func encode(to encoder: Encoder) throws {

        var container = encoder.container(keyedBy: String.self)

        try container.encode(path, forKey: "Path")
    }

    // Decodable protocol methods

    public required init(from decoder: Decoder) throws {
        let container = try decoder.container(keyedBy: String.self)

        path = try container.decode(String.self, forKey: "Path")
    }
}

